import type { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '../components/DesignSystemElements/Header';
import { Card } from '../components/DesignSystemElements/Card';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Card />
    </div>
  )
}

export default Home
